In [ ]:
import pandas as pd
import numpy as np

In [ ]:
students = pd.read_csv('students.csv')
nov = pd.read_csv('reg-month1.csv')
dec = pd.read_csv('reg-month2.csv')
courses = pd.read_csv('courses.csv')

In [ ]:
students.head(3)

   student_id            name  partner
0           1   Kailash Harjo       23
1           2     Esha Butala        1
2           3  Parveen Bhalla        3

In [ ]:
courses.head(3)

   course_id    course_name  price
0          1         python   2499
1          2            sql   3499
2          3  data analysis   4999

In [ ]:
nov.head(3)

   student_id  course_id
0          23          1
1          15          5
2          18          6

In [ ]:
dec.head(3)

   student_id  course_id
0           3          5
1          16          7
2          12         10

#pd.concat

In [ ]:
'''
pd.concat is just the vertical stacking of the 2 dfs. it is done when the 2 dfs are meant to be in separate dataframes but in the same
dataframe. both the dfs have same columns, suggesting that they both are 2 parts of the same table. hence, we just vertically stack them
to form one common table. in other words, you may understand it as a union operation between 2 tables to form 1 table.

use case:-
nov and dec are 2 tables having same type of content (same columns) suggesting that they are 2 parts of same table, hence we can
merge them to form a single table.
'''
pd.concat([nov,dec])

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9
5            7          7
6            7          2
7           16          3
8           17         10
9           11          8
10          14          6
11          12          5
12          12          7
13          18          8
14           1         10
15           1          9
16           2          5
17           7          6
18          22          5
19          22          6
20          23          9
21          23          5
22          14          4
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

In [ ]:
'''
but if we simply do pd.concat([nov,dec]), the concat operation will simply put one table below the other, everything in both the tables
remaining untouched. but here's the problem. even the indices are untouched, so after indices of nov from 0-24, the indices of dec from
0-27 starts. if we want to have something at index 0, 2 values are going to get fetched and it will be very difficult to identify them
uniquely.
'''
pd.concat([nov,dec]).loc[0]

   student_id  course_id
0          23          1
0           3          5

In [ ]:
'''
for unique identification of each entry after concant, we do:-
now, we can uniquely identify each row as when accessing through an index, we will get just 1 row instead of 2 rows having same index
previously.
'''
regs = pd.concat([nov,dec], ignore_index=True)
regs

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
25           3          5
26          16          7
27          12         10
28          12          1
29          14          9
30           7          7
31           7          2
32          16          3
33          17         10
34          11          8
35          14          6
36          12          5
37          12          7
38          18          8
39           1         10
40           1          9
41           2          5
42           7          6
43          22          5
44          22          6
45          23          9
46          23          5
47          14          4
48          14          1
49          11         10
50          42          9
51          50          8
52          38          1

#multi-index df (intro)

In [ ]:
'''
above, we are able to uniquely identify the rows, but what if we want to know whether it is coming from nov or dec?
'''
df = pd.concat([nov,dec], keys= ['Nov','Dec'])
#get student 5 details from nov:-
df.loc['Nov',5] #loc[index1, index2] or loc[filter, sub-filter]

student_id    18
course_id      1
Name: (Nov, 5), dtype: int64

#joins:-
1. inner
2. left
3. right
4. full

syntax:-
df.merge(another_df, how ='join_type', on='col')

In [ ]:
# inner join
students.merge(regs,how='inner',on='student_id')

    student_id                name  partner  course_id
0            1       Kailash Harjo       23          1
1            1       Kailash Harjo       23          6
2            1       Kailash Harjo       23         10
3            1       Kailash Harjo       23          9
4            2         Esha Butala        1          5
5            3      Parveen Bhalla        3          3
6            3      Parveen Bhalla        3          5
7            7        Tarun Thaker        9          8
8            7        Tarun Thaker        9         10
9            7        Tarun Thaker        9          7
10           7        Tarun Thaker        9          2
11           7        Tarun Thaker        9          6
12          11  David Mukhopadhyay       20          7
13          11  David Mukhopadhyay       20          8
14          11  David Mukhopadhyay       20         10
15          12          Radha Dutt       19         10
16          12          Radha Dutt       19          1
17          12          Radha Dutt       19          5
18          12          Radha Dutt       19          7
19          13      Munni Varghese       24          3
20          14    Pranab Natarajan       22          9
21          14    Pranab Natarajan       22          6
22          14    Pranab Natarajan       22          4
23          14    Pranab Natarajan       22          1
24          15           Preet Sha       16          5
25          15           Preet Sha       16          1
26          16        Elias Dodiya       25          9
27          16        Elias Dodiya       25          5
28          16        Elias Dodiya       25          7
29          16        Elias Dodiya       25          3
30          17        Yasmin Palan        7          7
31          17        Yasmin Palan        7         10
32          18     Fardeen Mahabir       13          6
33          18     Fardeen Mahabir       13          1
34          18     Fardeen Mahabir       13          8
35          19        Qabeel Raman       12          4
36          19        Qabeel Raman       12          2
37          21          Seema Kota       15          1
38          22          Yash Sethi       21          3
39          22          Yash Sethi       21          5
40          22          Yash Sethi       21          6
41          23      Chhavi Lachman       18          1
42          23      Chhavi Lachman       18          4
43          23      Chhavi Lachman       18          3
44          23      Chhavi Lachman       18          6
45          23      Chhavi Lachman       18          9
46          23      Chhavi Lachman       18          5
47          24        Radhika Suri       17          4
48          25     Shashank D’Alia        2          1
49          25     Shashank D’Alia        2         10

In [ ]:
# left join
courses.merge(regs,how='left',on='course_id')

    course_id       course_name  price  student_id
0           1            python   2499        23.0
1           1            python   2499        18.0
2           1            python   2499         1.0
3           1            python   2499        15.0
4           1            python   2499        21.0
5           1            python   2499        25.0
6           1            python   2499        12.0
7           1            python   2499        14.0
8           1            python   2499        38.0
9           2               sql   3499        19.0
10          2               sql   3499         7.0
11          3     data analysis   4999        22.0
12          3     data analysis   4999        13.0
13          3     data analysis   4999        23.0
14          3     data analysis   4999         3.0
15          3     data analysis   4999        16.0
16          4  machine learning   9999        23.0
17          4  machine learning   9999        19.0
18          4  machine learning   9999        24.0
19          4  machine learning   9999        14.0
20          5           tableau   2499        15.0
21          5           tableau   2499        16.0
22          5           tableau   2499         3.0
23          5           tableau   2499        12.0
24          5           tableau   2499         2.0
25          5           tableau   2499        22.0
26          5           tableau   2499        23.0
27          6          power bi   1899        18.0
28          6          power bi   1899         1.0
29          6          power bi   1899        23.0
30          6          power bi   1899        14.0
31          6          power bi   1899         7.0
32          6          power bi   1899        22.0
33          7          ms sxcel   1599        11.0
34          7          ms sxcel   1599        17.0
35          7          ms sxcel   1599        16.0
36          7          ms sxcel   1599         7.0
37          7          ms sxcel   1599        12.0
38          8            pandas   1099         7.0
39          8            pandas   1099        11.0
40          8            pandas   1099        18.0
41          8            pandas   1099        50.0
42          9            plotly    699        16.0
43          9            plotly    699        14.0
44          9            plotly    699         1.0
45          9            plotly    699        23.0
46          9            plotly    699        42.0
47         10           pyspark   2499         7.0
48         10           pyspark   2499        25.0
49         10           pyspark   2499        12.0
50         10           pyspark   2499        17.0
51         10           pyspark   2499         1.0
52         10           pyspark   2499        11.0
53         11             Numpy    699         NaN
54         12               C++   1299         NaN

In [ ]:
#right join
students.merge(regs,how='right',on='student_id')

    student_id                name  partner  course_id
0           23      Chhavi Lachman     18.0          1
1           15           Preet Sha     16.0          5
2           18     Fardeen Mahabir     13.0          6
3           23      Chhavi Lachman     18.0          4
4           16        Elias Dodiya     25.0          9
5           18     Fardeen Mahabir     13.0          1
6            1       Kailash Harjo     23.0          1
7            7        Tarun Thaker      9.0          8
8           22          Yash Sethi     21.0          3
9           15           Preet Sha     16.0          1
10          19        Qabeel Raman     12.0          4
11           1       Kailash Harjo     23.0          6
12           7        Tarun Thaker      9.0         10
13          11  David Mukhopadhyay     20.0          7
14          13      Munni Varghese     24.0          3
15          24        Radhika Suri     17.0          4
16          21          Seema Kota     15.0          1
17          16        Elias Dodiya     25.0          5
18          23      Chhavi Lachman     18.0          3
19          17        Yasmin Palan      7.0          7
20          23      Chhavi Lachman     18.0          6
21          25     Shashank D’Alia      2.0          1
22          19        Qabeel Raman     12.0          2
23          25     Shashank D’Alia      2.0         10
24           3      Parveen Bhalla      3.0          3
25           3      Parveen Bhalla      3.0          5
26          16        Elias Dodiya     25.0          7
27          12          Radha Dutt     19.0         10
28          12          Radha Dutt     19.0          1
29          14    Pranab Natarajan     22.0          9
30           7        Tarun Thaker      9.0          7
31           7        Tarun Thaker      9.0          2
32          16        Elias Dodiya     25.0          3
33          17        Yasmin Palan      7.0         10
34          11  David Mukhopadhyay     20.0          8
35          14    Pranab Natarajan     22.0          6
36          12          Radha Dutt     19.0          5
37          12          Radha Dutt     19.0          7
38          18     Fardeen Mahabir     13.0          8
39           1       Kailash Harjo     23.0         10
40           1       Kailash Harjo     23.0          9
41           2         Esha Butala      1.0          5
42           7        Tarun Thaker      9.0          6
43          22          Yash Sethi     21.0          5
44          22          Yash Sethi     21.0          6
45          23      Chhavi Lachman     18.0          9
46          23      Chhavi Lachman     18.0          5
47          14    Pranab Natarajan     22.0          4
48          14    Pranab Natarajan     22.0          1
49          11  David Mukhopadhyay     20.0         10
50          42                 NaN      NaN          9
51          50                 NaN      NaN          8
52          38                 NaN      NaN          1

In [ ]:
# outer join
students.merge(regs,how='outer',on='student_id').tail(10)

    student_id             name  partner  course_id
50          23   Chhavi Lachman     18.0        3.0
51          23   Chhavi Lachman     18.0        6.0
52          23   Chhavi Lachman     18.0        9.0
53          23   Chhavi Lachman     18.0        5.0
54          24     Radhika Suri     17.0        4.0
55          25  Shashank D’Alia      2.0        1.0
56          25  Shashank D’Alia      2.0       10.0
57          38              NaN      NaN        1.0
58          42              NaN      NaN        9.0
59          50              NaN      NaN        8.0

#practice questions

In [ ]:
# 1. find total revenue generated
df1 = courses.merge(regs,how='left',on='course_id')
df1['price'].sum()

np.int64(156245)

In [ ]:
# 2. find month by month revenue
regs = pd.concat([nov,dec],keys=['nov','dec']).reset_index()
regs
regs.merge(courses, on='course_id').groupby('level_0').sum(numeric_only=True)['price']

level_0
dec    65072
nov    89175
Name: price, dtype: int64

In [ ]:
# 3. find students who enrolled in both the months
'''
after doing groupby, when do we get a df and when a series?
NOTE:- any column selected in the groupby() becomes index/indices of df or series depending on the following:-
1. when df?
when we do:-
mask = df.groupby(['student_id', 'level_0']).count()
this is grouping + aggregation "WITHOUT" selecting a column.
student_id and level_0 became indices of the df.

2. when series?
when we do:-
mask = df.groupby(['student_id', 'level_0'])['level_0'].count()
this is grouping + aggregation "WITH" selecting a single column then obviously we are going to get a series only.
student_id and level_0 became indices of the series.

where columns inside the groupby become index/indices and when you apply a method, the values
obtained from method becomes the value column/s of the series/df.
but when you reset the index, the student_id and level_0 become columns again from indices, and the value column is given a name called
cnt.
'''

'''
set operations:-
np.union1d()        ------> for merging everyting
np.intersect1d()    ------> for finding common items
np.setdiff1d()      ------> for finding items which are in left table and not in right table.
'''

common_student_list = np.intersect1d(nov['student_id'], dec['student_id'])
df_new = students[students['student_id'].isin(common_student_list)]
df_new

    student_id                name  partner
0            1       Kailash Harjo       23
2            3      Parveen Bhalla        3
6            7        Tarun Thaker        9
10          11  David Mukhopadhyay       20
15          16        Elias Dodiya       25
16          17        Yasmin Palan        7
17          18     Fardeen Mahabir       13
21          22          Yash Sethi       21
22          23      Chhavi Lachman       18

In [ ]:
# 4. find course that got no enrollment
'''
regs contains students and corresponding course_id of courses registered.
courses contains all courses and corresponding ids.
we simply do a set diff between course_id of (courses and regs) which will omit all common course_ids of courses and regs and will just
keep the course_ids of courses which weren't common.
'''
regs = pd.concat([nov,dec])
regs
courses_not_reg_list = np.setdiff1d(courses['course_id'],regs['course_id'] )
courses[courses['course_id'].isin(courses_not_reg_list)]

    course_id course_name  price
10         11       Numpy    699
11         12         C++   1299

In [ ]:
# 5. find students who did not enroll into any courses
student_not_reg_list = np.setdiff1d(students['student_id'],regs['student_id'])
students[students['student_id'].isin(student_not_reg_list)]#.shape[0]*100/students.shape[0]

28.0

In [ ]:
# 6. Print student name -> partner name for all enrolled students
'''
when the columns names to be joined are different, left_on and right_on to be used.
'''
students.merge(students, how = 'inner', left_on = 'partner', right_on = 'student_id').head(3)

,student_id_x,name_x,partner_x,student_id_y,name_y,partner_y
0,1,Kailash Harjo,23,23,Chhavi Lachman,18
1,2,Esha Butala,1,1,Kailash Harjo,23
2,3,Parveen Bhalla,3,3,Parveen Bhalla,3

In [ ]:
# 7. find top 3 students who did most number enrollments
mask = regs.groupby('student_id')['course_id'].count().reset_index().head(3)
mask.merge(students, how = 'left', on = 'student_id')['name']

0     Kailash Harjo
1       Esha Butala
2    Parveen Bhalla
Name: name, dtype: object

In [ ]:
# 8. find top 3 student names who spent most amount of money on courses
mask = regs.merge(courses, how = 'left', on = 'course_id').groupby('student_id')['price'].sum().sort_values(ascending=False).head(3).reset_index()
mask.merge(students, how = 'left', on='student_id')['name']

0      Chhavi Lachman
1    Pranab Natarajan
2        Qabeel Raman
Name: name, dtype: object