In [ ]:
import numpy as np
import pandas as pd

In [ ]:
ipl = pd.read_csv('deliveries.csv')
movies = pd.read_csv('imdb-top-1000.csv')

In [ ]:
movies.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

#groupby

In [ ]:
genre = movies.groupby('Genre')
genre
type(genre) #when group by is done, we would get the df only.

pandas.core.groupby.generic.DataFrameGroupBy

In [ ]:
#when doing the following operations, keep numeric_only true for preventing errors.
genre.sum(numeric_only=True)
genre.mean(numeric_only=True)
genre.std(numeric_only=True)
genre.var(numeric_only=True)

#here, its okay as we might need the text in asc or desc order.
genre.min()
genre.max()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Yôjinbô,2019,321,9.0,Zack Snyder,Yun-Fat Chow,2303232,936662225.0,98.0
Adventure,Zombieland,PG,228,8.6,Ömer Faruk Sorak,Yves Montand,1512360,874211619.0,100.0
Animation,Ôkami kodomo no Ame to Yuki,2020,137,8.6,Yoshifumi Kondô,Yôji Matsuda,999790,873839108.0,96.0
Biography,Zerkalo,2020,209,8.9,Tom McCarthy,Éric Toledano,1213505,753585104.0,97.0
Comedy,Zindagi Na Milegi Dobara,2020,188,8.6,Zoya Akhtar,Ömer Faruk Sorak,939631,886752933.0,99.0
Crime,À bout de souffle,2019,229,9.2,Yavuz Turgul,Vincent Cassel,1826188,790482117.0,100.0
Drama,Zwartboek,2020,242,9.3,Çagan Irmak,Çetin Tekindor,2343110,924558264.0,100.0
Family,Willy Wonka & the Chocolate Factory,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Nosferatu,1922,94,8.1,Robert Wiene,Werner Krauss,88794,445151978.0,NaN
Film-Noir,The Third Man,1949,108,8.1,John Huston,Teresa Wright,158731,123353292.0,97.0
Horror,The Thing,2017,122,8.5,William Friedkin,Sigourney Weaver,787806,298791505.0,97.0
Mystery,Vertigo,2012,138,8.4,Terry Gilliam,Vidya Balan,1129894,474203697.0,100.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,165,8.8,Sergio Leone,Henry Fonda,688390,31800000.0,90.0

#practice questions

In [ ]:
# find the top 3 genres by total earning
genre.sum(numeric_only=True)['Gross'].sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [ ]:
# find the genre with highest avg IMDB rating
genre.mean(numeric_only=True)['IMDB_Rating'].sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [ ]:
# find director with most popularity (highest number of votes)
#genre.sum(numeric_only=True)['No_of_Votes'].sort_values(ascending=False).head(1)
movies.groupby('Director').sum(numeric_only = True)['No_of_Votes'].sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [ ]:
# find number of movies done by each actor
#whenever to count the number of items, just do groupby first, and then, pick any one column of the table and apply count() method.
movies.groupby('Star1')['Series_Title'].count()

Star1
Aamir Khan              7
Aaron Taylor-Johnson    1
Abhay Deol              1
Abraham Attah           1
Adam Driver             1
                       ..
Zbigniew Zamachowski    1
Zooey Deschanel         1
Çetin Tekindor          1
Éric Toledano           1
Ömer Faruk Sorak        1
Name: Series_Title, Length: 660, dtype: int64

#groupby attributes and methods

* len()
* size()
* first()/last() -> nth item
* get_group -> vs filtering
* groups
* describe()
* sample()
*nunique()

In [ ]:
#len
#gives us total number of genres/groups
len(movies.groupby('Genre'))

14

In [ ]:
#size
#gives us total number of items in each genre.
movies.groupby('Genre').size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [ ]:
#first, last, or nth item in the group
genres = movies.groupby('Genre')
genres.first() #gives first item/row of each group, not necessarily the smallest or biggest as not ordered.
genres.last() #gives last item/row of each group
genres.nth(6) #7th item/row of each group

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
16,Star Wars: Episode V - The Empire Strikes Back,1980,124,Action,8.7,Irvin Kershner,Mark Hamill,1159315,290475067.0,82.0
27,Se7en,1995,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.0
32,It's a Wonderful Life,1946,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199.0,89.0
66,WALL·E,2008,98,Animation,8.4,Andrew Stanton,Ben Burtt,999790,223808164.0,95.0
83,The Great Dictator,1940,125,Comedy,8.4,Charles Chaplin,Charles Chaplin,203150,288475.0,NaN
102,Braveheart,1995,178,Biography,8.3,Mel Gibson,Mel Gibson,959181,75600000.0,68.0
118,North by Northwest,1959,136,Adventure,8.3,Alfred Hitchcock,Cary Grant,299198,13275000.0,98.0
420,Sleuth,1972,138,Mystery,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,NaN
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0

In [ ]:
#get_group
genres.get_group('Fantasy')
'''
each group in itself is a df. so, when we have say the original df being divided into 14 different genres, each genre group is
also a df. hence, Fantasy group is a df.
'''

'\neach group in itself is a df. so, when we have say the original df being divided into 14 different genres, each genre group is\nalso a df. hence, Fantasy group is a df.\n'

In [ ]:
#describe()
'''
gives all the mathematical calculations for each group, be it min, max, q1, q3, median, mean, etc.
'''
genres.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [ ]:
#sample
#gives n random samples.
#replace=True because a genre may sample size < 2, and hence if sample size = 1 and we demanded 2 samples, we will get a copy of that one sample.
genres.sample(2,replace=True)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
152,V for Vendetta,2005,132,Action,8.2,James McTeigue,Hugo Weaving,1032749,70511035.0,62.0
369,Kill Bill: Vol. 2,2004,137,Action,8.0,Quentin Tarantino,Uma Thurman,683900,66208183.0,83.0
604,Captain Phillips,2013,134,Adventure,7.8,Paul Greengrass,Tom Hanks,421244,107100855.0,82.0
884,The Peanut Butter Falcon,2019,97,Adventure,7.6,Tyler Nilson,Michael Schwartz,66346,13122642.0,70.0
219,Song of the Sea,2014,93,Animation,8.1,Tomm Moore,David Rawle,51679,857524.0,85.0
672,Majo no takkyûbin,1989,103,Animation,7.8,Hayao Miyazaki,Kirsten Dunst,124193,58564351.0,83.0
657,Ed Wood,1994,127,Biography,7.8,Tim Burton,Johnny Depp,164937,5887457.0,70.0
282,Zerkalo,1975,107,Biography,8.1,Andrei Tarkovsky,Margarita Terekhova,40081,177345.0,NaN
594,English Vinglish,2012,134,Comedy,7.8,Gauri Shinde,Sridevi,33618,1670773.0,NaN
472,Sing Street,2016,106,Comedy,7.9,John Carney,Ferdia Walsh-Peelo,85109,3237118.0,79.0
775,Crash,2004,112,Crime,7.7,Paul Haggis,Don Cheadle,419483,54580300.0,66.0
239,Salinui chueok,2003,131,Crime,8.1,Bong Joon Ho,Kang-ho Song,139558,14131.0,82.0
793,Billy Elliot,2000,110,Drama,7.7,Stephen Daldry,Jamie Bell,126770,21995263.0,74.0
824,A Few Good Men,1992,138,Drama,7.7,Rob Reiner,Tom Cruise,235388,141340178.0,62.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
712,Shadow of a Doubt,1943,108,Film-Noir,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
712,Shadow of a Doubt,1943,108,Film-Noir,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
119,Vertigo,1958,128,Mystery,8.3,Alfred Hitchcock,James Stewart,364368,3200000.0,100.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [ ]:
'''
counts unique items in each genre. it is similar to size().
size() just returns total size of each group, without eliminating the non unique occurences.
whereas, nunique counts the unique number of items in each group and for each column of that group.
'''
genres.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

#aggregate methods ---> .agg()

In [ ]:
#agg() can have a dictionary or a list inside

#passing dict:-  agg({})
'''
when you want to have different aggregate functions being applied on different columns, but at the same time, we use dictionary.
'''
genres.agg({
    'Runtime':'mean',
    'IMDB_Rating':'mean',
    'No_of_Votes':'sum',
    'Gross':'sum',
    'Metascore':'min'
})

              Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419     72282412  3.263226e+10       33.0
Adventure  134.111111     7.937500     22576163  9.496922e+09       41.0
Animation   99.585366     7.930488     21978630  1.463147e+10       61.0
Biography  136.022727     7.938636     24006844  8.276358e+09       48.0
Comedy     112.129032     7.901290     27620327  1.566387e+10       45.0
Crime      126.392523     8.016822     33533615  8.452632e+09       47.0
Drama      124.737024     7.957439     61367304  3.540997e+10       28.0
Family     107.500000     7.800000       551221  4.391106e+08       67.0
Fantasy     85.000000     8.000000       146222  7.827267e+08        NaN
Film-Noir  104.000000     7.966667       367215  1.259105e+08       94.0
Horror     102.090909     7.909091      3742556  1.034649e+09       46.0
Mystery    119.083333     7.975000      4203004  1.256417e+09       52.0
Thriller   108.000000     7.800000        27733  1.755074e+07       81.0
Western    148.250000     8.350000      1289665  5.822151e+07       69.0

In [ ]:
#passing list:- agg([])
'''
when passing agg in form of list, it applies all the mentioned functions to each column. so if some column is non-nnumeric, it will
show errors in case of mean. so, firstly select all the numeric columns and then apply agg.
this is not like passing dict in agg, where you can select what function to apply where.
'''
movies.select_dtypes(include='number').groupby(movies['Genre']).agg(['min', 'max', 'mean'])

          Runtime                  IMDB_Rating                No_of_Votes  \
              min  max        mean         min  max      mean         min
Genre
Action         45  321  129.046512         7.6  9.0  7.949419       25312
Adventure      88  228  134.111111         7.6  8.6  7.937500       29999
Animation      71  137   99.585366         7.6  8.6  7.930488       25229
Biography      93  209  136.022727         7.6  8.9  7.938636       27254
Comedy         68  188  112.129032         7.6  8.6  7.901290       26337
Crime          80  229  126.392523         7.6  9.2  8.016822       27712
Drama          64  242  124.737024         7.6  9.3  7.957439       25088
Family        100  115  107.500000         7.8  7.8  7.800000      178731
Fantasy        76   94   85.000000         7.9  8.1  8.000000       57428
Film-Noir     100  108  104.000000         7.8  8.1  7.966667       59556
Horror         71  122  102.090909         7.6  8.5  7.909091       27007
Mystery        96  138  119.083333         7.6  8.4  7.975000       33982
Thriller      108  108  108.000000         7.8  7.8  7.800000       27733
Western       132  165  148.250000         7.8  8.8  8.350000       65659

                                         Gross                             \
               max           mean          min          max          mean
Genre
Action     2303232  420246.581395       3296.0  936662225.0  1.897224e+08
Adventure  1512360  313557.819444      61001.0  874211619.0  1.319017e+08
Animation   999790  268032.073171     128985.0  873839108.0  1.784326e+08
Biography  1213505  272805.045455      21877.0  753585104.0  9.404952e+07
Comedy      939631  178195.658065       1305.0  886752933.0  1.010572e+08
Crime      1826188  313398.271028       6013.0  790482117.0  7.899656e+07
Drama      2343110  212343.612457       3600.0  924558264.0  1.225259e+08
Family      372490  275610.500000    4000000.0  435110554.0  2.195553e+08
Fantasy      88794   73111.000000  337574718.0  445151978.0  3.913633e+08
Film-Noir   158731  122405.000000     449191.0  123353292.0  4.197018e+07
Horror      787806  340232.363636      89029.0  298791505.0  9.405902e+07
Mystery    1129894  350250.333333    1035953.0  474203697.0  1.047014e+08
Thriller     27733   27733.000000   17550741.0   17550741.0  1.755074e+07
Western     688390  322416.250000    5321508.0   31800000.0  1.455538e+07

          Metascore
                min    max       mean
Genre
Action         33.0   98.0  73.419580
Adventure      41.0  100.0  78.437500
Animation      61.0   96.0  81.093333
Biography      48.0   97.0  76.240506
Comedy         45.0   99.0  78.720000
Crime          47.0  100.0  77.080460
Drama          28.0  100.0  79.701245
Family         67.0   91.0  79.000000
Fantasy         NaN    NaN        NaN
Film-Noir      94.0   97.0  95.666667
Horror         46.0   97.0  80.000000
Mystery        52.0  100.0  79.125000
Thriller       81.0   81.0  81.000000
Western        69.0   90.0  78.250000

In [ ]:
#using both, the list as well as the dict:-
genres.agg({
    'Runtime':['mean', 'sum'],
    'IMDB_Rating':'mean',
    'No_of_Votes':['min','sum'],
    'Gross':'sum',
    'Metascore':'min'
})

              Runtime        IMDB_Rating No_of_Votes                   Gross  \
                 mean    sum        mean         min       sum           sum
Genre
Action     129.046512  22196    7.949419       25312  72282412  3.263226e+10
Adventure  134.111111   9656    7.937500       29999  22576163  9.496922e+09
Animation   99.585366   8166    7.930488       25229  21978630  1.463147e+10
Biography  136.022727  11970    7.938636       27254  24006844  8.276358e+09
Comedy     112.129032  17380    7.901290       26337  27620327  1.566387e+10
Crime      126.392523  13524    8.016822       27712  33533615  8.452632e+09
Drama      124.737024  36049    7.957439       25088  61367304  3.540997e+10
Family     107.500000    215    7.800000      178731    551221  4.391106e+08
Fantasy     85.000000    170    8.000000       57428    146222  7.827267e+08
Film-Noir  104.000000    312    7.966667       59556    367215  1.259105e+08
Horror     102.090909   1123    7.909091       27007   3742556  1.034649e+09
Mystery    119.083333   1429    7.975000       33982   4203004  1.256417e+09
Thriller   108.000000    108    7.800000       27733     27733  1.755074e+07
Western    148.250000    593    8.350000       65659   1289665  5.822151e+07

          Metascore
                min
Genre
Action         33.0
Adventure      41.0
Animation      61.0
Biography      48.0
Comedy         45.0
Crime          47.0
Drama          28.0
Family         67.0
Fantasy         NaN
Film-Noir      94.0
Horror         46.0
Mystery        52.0
Thriller       81.0
Western        69.0

#looping in groups

In [ ]:
#find the movie details where imdb rating of that movie is the max in each group.
'''
for group,df in genres: ---> this means that we are going to each group's df.
in that df, we need to select those rows where the imdb rating = max imdb rating of the whole column/series.
df[WHERE]
df[df['IMDB_Rating'] == df['IMDB_Rating'].max()]
this will give us row/rows of movie details in the form of dataframe that we append in the list.
at last, we simply concatenate the whole list into the new dataframe, which is, new df.
'''
new_df_list = []
for group,df in genres:
  new_df_list.append(df[df['IMDB_Rating'] == df['IMDB_Rating'].max()])

new_df = pd.concat(new_df_list)
new_df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

#apply after groupby

---
1. "**split**" using groupby
2. "**apply**" a function
3. "**combine**" the resultant to the original dataframe

In [ ]:
# find number of movies starting with A for each group

def check (group):
  cnt = group['Series_Title'].str.startswith('A').sum()
  return cnt

genres.apply(check)

/tmp/ipython-input-21-4067657546.py:7: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(check)

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [ ]:
# find ranking of each movie in the group according to IMDB score
def give_rank(group):
  group['rank'] = group['IMDB_Rating'].rank(ascending=False)
  return group

genres.apply(give_rank)

/tmp/ipython-input-24-2306559955.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(give_rank)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  rank
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0   1.0
         5          Elijah Wood      1642758  377845905.0       94.0   2.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0   3.5
         10         Elijah Wood      1661481  315544750.0       92.0   3.5
         13         Elijah Wood      1485555  342551365.0       87.0   6.0
...                         ...          ...          ...        ...   ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0   1.0
Western  12      Clint Eastwood       688390    6100000.0       90.0   1.0
         48         Henry Fonda       302844    5321508.0       80.0   2.0
         115     Clint Eastwood       232772   15000000.0       74.0   3.0
         691     Clint Eastwood        65659   31800000.0       69.0   4.0

[1000 rows x 11 columns]

In [ ]:
# find normalized IMDB rating group wise
'''
normalized value = (X-Xmin)/(Xmax - Xmin)
'''
def normalize(group):
  group['normalized_rating'] = (group['IMDB_Rating'] - group['IMDB_Rating'].min())/(group['IMDB_Rating'].max() - group['IMDB_Rating'].min())
  return group

genres.apply(normalize)

/tmp/ipython-input-27-2398208482.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(normalize)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              normalized_rating
Genre
Action   2             1.000000
         5             0.928571
         8             0.857143
         10            0.857143
         13            0.785714
...                         ...
Thriller 700                NaN
Western  12            1.000000
         48            0.700000
         115           0.500000
         691           0.000000

[1000 rows x 11 columns]

#groupby on multiple columns

In [ ]:
duo = movies.groupby(['Director','Star1'])
len(duo)
duo.size()
duo.get_group(('Aamir Khan', 'Amole Gupte'))

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
65,Taare Zameen Par,2007,165,Drama,8.4,Aamir Khan,Amole Gupte,168895,1223869.0,NaN

In [ ]:
# find the most earning actor-director combination
duo.sum(numeric_only=True)['Gross'].sort_values(ascending=False).head(1)

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Name: Gross, dtype: float64

In [ ]:
# find the best(in-terms of metascore(avg)) actor-genre combination
duo2 = movies.groupby(['Star1','Genre'])
duo2.mean(numeric_only= True)['Metascore'].sort_values(ascending=False).head(1)

Star1          Genre
Peter O'Toole  Adventure    100.0
Name: Metascore, dtype: float64

In [ ]:
# agg on multiple groupby
duo.agg(['min','max'])

                                                  Series_Title  \
                                                           min
Director            Star1
Aamir Khan          Amole Gupte               Taare Zameen Par
Aaron Sorkin        Eddie Redmayne  The Trial of the Chicago 7
Abdellatif Kechiche Léa Seydoux                 La vie d'Adèle
Abhishek Chaubey    Shahid Kapoor                  Udta Punjab
Abhishek Kapoor     Amit Sadh                      Kai po che!
...                                                        ...
Zaza Urushadze      Lembit Ulfsak                  Mandariinid
Zoya Akhtar         Hrithik Roshan    Zindagi Na Milegi Dobara
                    Vijay Varma                      Gully Boy
Çagan Irmak         Çetin Tekindor              Babam ve Oglum
Ömer Faruk Sorak    Cem Yilmaz                        G.O.R.A.

                                                               Released_Year  \
                                                           max           min
Director            Star1
Aamir Khan          Amole Gupte               Taare Zameen Par          2007
Aaron Sorkin        Eddie Redmayne  The Trial of the Chicago 7          2020
Abdellatif Kechiche Léa Seydoux                 La vie d'Adèle          2013
Abhishek Chaubey    Shahid Kapoor                  Udta Punjab          2016
Abhishek Kapoor     Amit Sadh                      Kai po che!          2013
...                                                        ...           ...
Zaza Urushadze      Lembit Ulfsak                  Mandariinid          2013
Zoya Akhtar         Hrithik Roshan    Zindagi Na Milegi Dobara          2011
                    Vijay Varma                      Gully Boy          2019
Çagan Irmak         Çetin Tekindor              Babam ve Oglum          2005
Ömer Faruk Sorak    Cem Yilmaz                        G.O.R.A.          2004

                                         Runtime           Genre             \
                                     max     min  max        min        max
Director            Star1
Aamir Khan          Amole Gupte     2007     165  165      Drama      Drama
Aaron Sorkin        Eddie Redmayne  2020     129  129      Drama      Drama
Abdellatif Kechiche Léa Seydoux     2013     180  180      Drama      Drama
Abhishek Chaubey    Shahid Kapoor   2016     148  148     Action     Action
Abhishek Kapoor     Amit Sadh       2013     130  130      Drama      Drama
...                                  ...     ...  ...        ...        ...
Zaza Urushadze      Lembit Ulfsak   2013      87   87      Drama      Drama
Zoya Akhtar         Hrithik Roshan  2011     155  155     Comedy     Comedy
                    Vijay Varma     2019     154  154      Drama      Drama
Çagan Irmak         Çetin Tekindor  2005     112  112      Drama      Drama
Ömer Faruk Sorak    Cem Yilmaz      2004     127  127  Adventure  Adventure

                                   IMDB_Rating      No_of_Votes          \
                                           min  max         min     max
Director            Star1
Aamir Khan          Amole Gupte            8.4  8.4      168895  168895
Aaron Sorkin        Eddie Redmayne         7.8  7.8       89896   89896
Abdellatif Kechiche Léa Seydoux            7.7  7.7      138741  138741
Abhishek Chaubey    Shahid Kapoor          7.8  7.8       27175   27175
Abhishek Kapoor     Amit Sadh              7.7  7.7       32628   32628
...                                        ...  ...         ...     ...
Zaza Urushadze      Lembit Ulfsak          8.2  8.2       40382   40382
Zoya Akhtar         Hrithik Roshan         8.1  8.1       67927   67927
                    Vijay Varma            8.0  8.0       31886   31886
Çagan Irmak         Çetin Tekindor         8.3  8.3       78925   78925
Ömer Faruk Sorak    Cem Yilmaz             8.0  8.0       56960   56960

                                          Gross              Metascore
                                            min          max       min   max
Director            Star1
Aamir Khan          Amole Gupte       1223869.0    1223869.0       NaN   NaN
Aaron Sorkin        Eddie Redmayne  853090410.0  853090410.0      77.0  77.0
Abdellatif Kechiche Léa Seydoux       2199675.0    2199675.0      89.0  89.0
Abhishek Chaubey    Shahid Kapoor   218428303.0  218428303.0       NaN   NaN
Abhishek Kapoor     Amit Sadh         1122527.0    1122527.0      40.0  40.0
...                                         ...          ...       ...   ...
Zaza Urushadze      Lembit Ulfsak      144501.0     144501.0      73.0  73.0
Zoya Akhtar         Hrithik Roshan    3108485.0    3108485.0       NaN   NaN
                    Vijay Varma       5566534.0    5566534.0      65.0  65.0
Çagan Irmak         Çetin Tekindor  461855363.0  461855363.0       NaN   NaN
Ömer Faruk Sorak    Cem Yilmaz      196206077.0  196206077.0       NaN   NaN

[898 rows x 16 columns]

In [ ]:
ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [ ]:
# find the top 10 batsman in terms of runs
batter = ipl.groupby('batsman')
batter.sum(numeric_only=True)['batsman_runs'].sort_values(ascending=False).head(10)

batsman
V Kohli           5434
SK Raina          5415
RG Sharma         4914
DA Warner         4741
S Dhawan          4632
CH Gayle          4560
MS Dhoni          4477
RV Uthappa        4446
AB de Villiers    4428
G Gambhir         4223
Name: batsman_runs, dtype: int64

In [ ]:
# find the batsman with max no of sixes
mask = ipl[ipl['batsman_runs'] == 6]
sixer = mask.groupby('batsman')
sixer['batsman_runs'].count().sort_values(ascending=False).head(1)

batsman
CH Gayle    327
Name: batsman_runs, dtype: int64

In [ ]:
# find batsman with most number of 4's and 6's in last 5 overs
mask = ipl[(ipl['over'] > 15) & ((ipl['batsman_runs']==4) | (ipl['batsman_runs']==6))]
mask.groupby('batsman')['batsman_runs'].count().sort_values(ascending=False).head(1)

batsman
MS Dhoni    340
Name: batsman_runs, dtype: int64

In [ ]:
'''
after doing groupby, when do we get a df and when a series?
NOTE:- any column selected in the groupby() becomes index/indices of df or series depending on the following:-
1. when df?
when we do:-
mask = df.groupby(['student_id', 'level_0']).count()
this is grouping + aggregation "WITHOUT" selecting a column.
student_id and level_0 became indices of the df.

2. when series?
when we do:-
mask = df.groupby(['student_id', 'level_0'])['level_0'].count()
this is grouping + aggregation "WITH" selecting a single column then obviously we are going to get a series only.
student_id and level_0 became indices of the series.

where columns inside the groupby become index/indices and when you apply a method, the values
obtained from method becomes the value column/s of the series/df.
but when you reset the index, the student_id and level_0 become columns again from indices, and the value column is given a name called
cnt.
'''